/**
 * Re-export shared API/domain types (replaces alias to `frontend/src/lib/types`).
 */
export type {
  ApiError,
  Aspect,
  AspectType,
  AuthResult,
  AuthUser,
  BirthProfile,
  City,
  CompatibilityResult,
  DailyHoroscope,
  GlobalSkyCard,
  GlobalSkyToday,
  AtmosphereKey,
  PersonalSkyLayer,
  PersonalSkyRitualCard,
  HoroscopeReading,
  HouseCusp,
  LoginPayload,
  NatalChart,
  NotificationPreferences,
  NotificationPreferencesUpdate,
  PlanetName,
  PlanetPosition,
  ProfilePayload,
  PushTokenRegistrationPayload,
  RegisterPayload,
  RitualHistoryDay,
  TarotApiResponse,
  TarotCard,
  TarotPublicCard,
  TarotPublicReading,
  TarotReading,
  ZodiacInfo,
  ZodiacSign,
} from '@horoscope/shared';
